---
title: "Capstone EDA"
author: "Jenna Ford, Christian Nava, Jonathan Tan"
date: "5/21/2020"
output:
  rmdformats::readthedown:
    highlight: kate
---

```{r setup, include=FALSE}
library(rmdformats)
library(tidyverse)  # data manipulaiton
library(data.table)
library(tswge)  # Time series package
library(tseries)  # for Dickey-Fuller test 
library(orcutt)  # for Cochrane-Orcutt test
library(formattable)  # for table formatting
library(GGally)
library(astsa)
library(nnfor)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE,
               prompt = FALSE,
               tidy = TRUE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
```

***
# Time Series Analysis of Corpus Christi Liquor Distribution
***
Jenna Ford, Christian Nava and Jonathan Tan  
May 21, 2020


## Read in Datasets and Combine
***
```{r data}
df_17_19 = read.csv("C:/Users/b007224/Documents/masters_in_data_science/capstone/data/Bivin CC 2017-19_updated_headings.csv")
df_15_16 = read.csv("C:/Users/b007224/Documents/masters_in_data_science/capstone/data/Bivin CC 2015-16_updated_headings.csv")
df_13_14 = read.csv("C:/Users/b007224/Documents/masters_in_data_science/capstone/data/Bivin CC 2013-14_updated_headings.csv")

dim(df_17_19)
dim(df_15_16)
dim(df_13_14)

df <- rbind(df_17_19,df_15_16,df_13_14)

dim(df)
```

## Check for Missing Data
***
Here we create a function to check for missing data.
```{r missing}
check.for.missing.data <- function(data){
  a = colnames(data)
  b = colSums(is.na(df))  %>% as.data.table
  missing_value_table = cbind(a, b)
  colnames(missing_value_table) = c("Variables","Missing_values")
  missing_value_table = missing_value_table  %>% filter(Missing_values>0)  %>% 
                        mutate("As a % of Total Values" = round(100 * (Missing_values / nrow(df)), 1))  %>% 
                        arrange(desc(Missing_values))
  head(missing_value_table, 20)
}

table_a = check.for.missing.data(data=df)
# display table with first column aligned left all others aligned right
formattable(table_a, align = c("l", rep("r", NCOL(table_a) - 1)))
```

## Drop `Metrics` Variable
***

```{r drop}
drops <- c("Metrics")
df = df[ , !(names(df) %in% drops)]
```

## Variable Formatting
***

```{r formatting}
str(df)
```

## Products
***

```{r products}
df %>% group_by(Product_Type) %>% tally(sort=TRUE)
df %>% group_by(Product_Type, Product) %>% tally(sort=TRUE)
```