---
title: "Capstone"
author: "Jenna Ford, Christian Nava, Jonathan Tan"
date: "5/21/2020"
output:
  rmdformats::readthedown:
    highlight: kate
---

```{r setup, include=FALSE}
library(rmdformats)
library(tidyverse)  # data manipulaiton
library(data.table)
library(tswge)  # Time series package
library(tseries)  # for Dickey-Fuller test 
library(orcutt)  # for Cochrane-Orcutt test
library(formattable)  # for table formatting
library(GGally)
library(astsa)
library(nnfor)
library(dplyr)
library(ggplot2)
library(changepoint)
library(date)
library(R.devices)
library(sjPlot)
knitr::opts_chunk$set(echo = TRUE,
               prompt = FALSE,
               tidy = TRUE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
```

***
# F Statistic Simulation
***
Jenna Ford, Christian Nava and Jonathan Tan  
May 21, 2020

```{r}
F_statistic_holder = numeric()
p_value_holder = numeric()
df_model_holder = numeric()
df_ARMA_holder = numeric()

for(j in 1:10000) {
  nulldev()
  x = gen.arma.wge(n=100)
  dev.off()

  #Equal Means Model
  sink("file")
  model0_mean = mean(x)
  EM_SSE = sum((x - model0_mean)^2)
  EM_SSE
  sink()
  
  #ARMA Model
  sink("file")
  #model1 = invisible(aic.wge(x,type="aic"))
  model1_est = tryCatch(est.arma.wge(x,p=1,q=1),error=function(e) NULL)
  
  ARMA_SSE = sum((model1_est$res)^2)
  ARMA_SSE
  sink()
 
  #ANOVA table
  df_EQ = 100 - 1
  df_ARMA = 100 - (1 + 1 + 1)
  df_model = df_EQ - df_ARMA
  
  SS_Model = EM_SSE - ARMA_SSE
  SS_Model
  MS_Model = SS_Model/df_model
  MS_ARMA = ARMA_SSE/df_ARMA
  F=MS_Model/MS_ARMA
  p_value = pf(F,df_model,df_ARMA)
  
  F_statistic_holder[j] = F
  p_value_holder[j] = p_value
  df_model_holder[j] = df_model
  df_ARMA_holder[j] = df_ARMA

}

ylim <- range(0,2.5)
xlim <- range(0,3)
x <- seq(0,6,0.01)
d <- density(F_statistic_holder)
plot(d,xlim=xlim,ylim=ylim,main="F-Statistic Distribution for Simulation",xlab="",col="blue")
curve(df(x,3,97),add=T,col='black')
legend(2.05,2.5,legend=c("Equal Means/ARMA","F Distribution DF=3,97"),col=c("blue","black"),lty=1:1, cex=0.8)
```

```{r}
F_statistic_holder = numeric()
p_value_holder = numeric()
df_model_holder = numeric()
df_ARMA_holder = numeric()

for(j in 1:10000) {
  nulldev()
  x = gen.arma.wge(n=100)
  dev.off()

  #Equal Means Model
  sink("file")
  model0_mean = mean(x)
  EM_SSE = sum((x - model0_mean)^2)
  sink()
  
  #ARMA Model
  sink("file")
  #model1 = invisible(aic.wge(x,type="aic"))
  model1_est = tryCatch(est.arma.wge(x,p=2,q=2),error=function(e) NULL)
  
  ARMA_SSE = sum((model1_est$res)^2)
  sink()
 
  #ANOVA table
  df_EQ = 60 - 1
  df_ARMA = 59 - (model1$p + model1$q + 1)
  df_model = df_EQ - df_ARMA
  
  SS_Model = EM_SSE - ARMA_SSE
  MS_Model = SS_Model/df_model
  MS_ARMA = ARMA_SSE/df_ARMA
  F=MS_Model/MS_ARMA
  p_value = pf(F,df_model,df_ARMA)
  
  F_statistic_holder[j] = F
  p_value_holder[j] = p_value
  df_model_holder[j] = df_model
  df_ARMA_holder[j] = df_ARMA

}

ylim <- range(0,2.5)
xlim <- range(0,3)
x <- seq(0,6,0.01)
d <- density(F_statistic_holder)
plot(d,xlim=xlim,ylim=ylim,main="F-Statistic Distribution for Equal Means/ARMA Residuals",xlab="",col="blue")
curve(df(x,5,54),add=T,col='blue')
#legend(4,2,legend=c("Equal Means/ARMA","F Distribution DF=2,57"),col=c("black","blue"),lty=1:1, cex=0.8)
```

```{r}
F_statistic_holder = numeric()
p_value_holder = numeric()
df_model_holder = numeric()
df_ARMA_holder = numeric()

for(j in 1:10000) {
  nulldev()
  x = gen.arma.wge(n=100)
  dev.off()

  #Equal Means Model
  sink("file")
  model0_mean = mean(x)
  EM_SSE = sum((x - model0_mean)^2)
  sink()
  
  #ARMA Model
  sink("file")
  #model1 = invisible(aic.wge(x,type="aic"))
 model1_est = tryCatch(est.arma.wge(x,p=3,q=3),error=function(e) NULL)
  
  ARMA_SSE = sum((model1_est$res)^2)
  sink()
 
  #ANOVA table
  df_EQ = 100 - 1
  df_ARMA = 99 - (3 + 3 + 1)
  df_model = df_EQ - df_ARMA
  
  SS_Model = EM_SSE - ARMA_SSE
  MS_Model = SS_Model/df_model
  MS_ARMA = ARMA_SSE/df_ARMA
  F=MS_Model/MS_ARMA
  p_value = pf(F,df_model,df_ARMA)
  
  F_statistic_holder[j] = F
  p_value_holder[j] = p_value
  df_model_holder[j] = df_model
  df_ARMA_holder[j] = df_ARMA

}

ylim <- range(0,2.5)
xlim <- range(0,3)
x <- seq(0,6,0.01)
d <- density(F_statistic_holder)
plot(d,xlim=xlim,ylim=ylim,main="F-Statistic Distribution for Equal Means/ARMA Residuals",xlab="",col="blue")
curve(df(x,2,57),add=T,col='blue')
legend(4,2,legend=c("Equal Means/ARMA","F Distribution DF=2,57"),col=c("black","blue"),lty=1:1, cex=0.8)
```


